spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


