spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: true
    web:
      exposure:
        include: '*'