spring:
  datasource:
    url: jdbc:mysql://mysql-docker-container:3306/taskmanager
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false




